//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleStopTimes
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleStopTimes { }
#else

	public class SampleStopTimes : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleStopTimes()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/GRTLookup;component/SampleData/SampleStopTimes/SampleStopTimes.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _ArrivalTime = string.Empty;

		public string ArrivalTime
		{
			get
			{
				return this._ArrivalTime;
			}

			set
			{
				if (this._ArrivalTime != value)
				{
					this._ArrivalTime = value;
					this.OnPropertyChanged("ArrivalTime");
				}
			}
		}

		private double _RouteId = 0;

		public double RouteId
		{
			get
			{
				return this._RouteId;
			}

			set
			{
				if (this._RouteId != value)
				{
					this._RouteId = value;
					this.OnPropertyChanged("RouteId");
				}
			}
		}

		private string _Headsign = string.Empty;

		public string Headsign
		{
			get
			{
				return this._Headsign;
			}

			set
			{
				if (this._Headsign != value)
				{
					this._Headsign = value;
					this.OnPropertyChanged("Headsign");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
